### ISSUE TITLE
default tab doesnt disappear when a tab pack is present

### ISSUE THREAD

**Issue by xemnes** [TeamElysia/ArtisansTabs#7]
ive created a tab pack, it appears in my creative menu perfectly with all the items i want in it
except the default tab is still there saying it hasnt found a tab pack
https://gfycat.com/AnchoredMarriedArawana

**Comment by TheUnknownFew** [comment]
I'll look into this issue. What version of MC are you running?

**Comment by xemnes** [comment]
1.10.2 
Artisan's Tabs - v-1.10.2-1.3.0.1

**Comment by TheUnknownFew** [comment]
I am unable to replicate this issue. Please tell me how you managed to encounter this issue.

**Comment by xemnes** [comment]
im not really sure to be honest, i didnt really do anything special. i first tried to create a tab pack using commands but stumbled upon the errors as mentioned before which stopped me. this is the first time i saw the default tab and just assumed it disappears when i create a tab pack.

i then created a tab pack manually and loaded it, my tab showed up but the default tab didnt disappear. i restarted minecraft thinking it was an initialisation problem but the problem persisted even after a restart.

my resource pack structure:
https://gfycat.com/FaroffPreciousGangesdolphin

(named it artisanstabs as it fits the resource pack naming conventions for mods, it was originally named 'paintings')

**Comment by TheUnknownFew** [comment]
can you send me the fml-client-latest please in the logs folder of your minecraft instance?

**Comment by xemnes** [comment]
yeah i kinda assumed that is how it works. i chose artisanstabs for now as it fits mod naming conventions in resource packs which i can use to easily identify what goes where in terms of mod files.


heres the log 
[fml-client-latest.txt](https://github.com/TeamElysia/ArtisansTabs/files/1236607/fml-client-latest.txt)

**Comment by xemnes** [comment]
update: i went into the mod jar and manually deleted the tab pack holding the default tab inside it and it worked. in all honesty, im not sure if its really necessary to even have that tab there. you have to read the documentation anyway and i understand that people may skip the reading and boot up the mod to find they have no idea what to do. 
my suggestion is just adding the info on where you can find the documention in the mod description in the mod options menu. up to you but i can see it saving a lot of hastle with fixing this :)

**Comment by TheUnknownFew** [comment]
I'll consider other options as to notifying people to actually read the documentation. I think a large issue is that the way I have it, ?I need identical text in two places and one typo can mess up whether or not the default tab displays or not, so that is most likely what is causing this issue. I'll see about it, about maybe adding an info button to the creative screen

**Comment by xemnes** [comment]
that would work, yeah ^^

**Comment by TheUnknownFew** [comment]
Fixed in the latest update
