### ISSUE TITLE
[suggestion] support for CACTI mod

### ISSUE THREAD

**Issue by xemnes** [TeamElysia/ArtisansTabs#9]
requesting support for the CACTI mods api integration which allows mod related tabs to be grouped into specific mod tabs

https://mods.curse.com/mc-mods/minecraft/248552-cacti-categorical-creative-inventory

![image](https://user-images.githubusercontent.com/603338/29488620-8d804e34-8506-11e7-985b-9ce98a78dd36.png)

currently when opening the tabs, it shows multiple tabs of the same tab. im not sure how flexible the CACTI api is but it would be really nice if it didnt look so messy as it currently does.

**Comment by TheUnknownFew** [comment]
I don't know much about CACTI, but I will give it a look and consider adding support for the mod

**Comment by xemnes** [comment]
they only duplicate like that in the artisans tabs category in cacti. unfortunately because cacti forces mod tab groups, every time i add a new tab it will add 3 duplicates of that tab to the ui. its fine if i disable the cacti mod.

**Comment by TheUnknownFew** [comment]
ah, so the duplication issue is a CACTI issue?

**Comment by xemnes** [comment]
yes

**Comment by xemnes** [comment]
thought id make an update on this, every time you reload the resource pack, it duplicates the tabs by one, ive found out that on startup, the resource pack reloads 3 times which is why theres 3 of each tab. eventually if you reload too many times, the game will crash.

**Comment by TheUnknownFew** [comment]
What version of the mod? Also thank you for the feed back. I knew this was an issue, but I had thought I had fixed it in the newer version of the mod.

**Comment by xemnes** [comment]
using this version of artisans tabs 1.3.0.2 and cacti 1.0.1 for mc v1.10.2

**Comment by xemnes** [comment]
any update for a new version to fix this update? dont want to rush you, im just curious.

**Comment by TheUnknownFew** [comment]
The update is still being worked on just as I mentioned before. I do not want to give an exact ETA as to when the fix will be implemented, but I know it wont be until after new years. I'm currently away from the machine that had the mod files.

**Comment by xemnes** [comment]
alright, thanks for the update. again, no rush.

**Comment by TheUnknownFew** [comment]
Sorry that it has been a while since the last update. I'm juggling between holiday matters, some educational studies, and other projects that im working on. I revisit the mod code every now and then so im still up to date with issues like this that im trying to fix. Thank you so much for your patients.

**Comment by xemnes** [comment]
its no problem at all, i completely understand. i can relate to christmas matters too :P

**Comment by TheUnknownFew** [comment]
Good news! The progress made on integrating cacti support has gone swimmingly. There shall be two new updates coming out soon. One update for 1.10.2 version of the mod which adds cacti support and an updated version of the mod for 1.12! I shall let you know once I'm fully done implementing cacti support.

**Comment by xemnes** [comment]
thats awesome to hear, thank you for the update!

**Comment by TheUnknownFew** [comment]
Here is a bit of a sneak peak to feed your thoughts ;) https://i.imgur.com/PjigJCc.png

**Comment by xemnes** [comment]
nice :D

**Comment by TheUnknownFew** [comment]
Cacti support ready for release some time tomorrow 1/14/2018 update 1.10.2  v1.3.0.3.

**Comment by TheUnknownFew** [comment]
https://minecraft.curseforge.com/projects/artisans-tabs/files/2520393

Cacti support added! You can get the update here. If you find any bugs, please make a new ticket.

**Comment by xemnes** [comment]
awesome! will start testing and will let you know if i run into any bugs
